# Generated by Django 5.2.4 on 2025-12-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Taller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(max_length=20)),
                ("direccion", models.CharField(max_length=255)),
                ("horarioAtencion", models.TimeField(blank=True, null=True)),
                ("cuit", models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
    ]
