# Generated by Django 5.2.4 on 2025-11-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talleres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taller",
            name="cuit",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="taller",
            name="horarioAtencion",
            field=models.TimeField(blank=True, default='08:00:00'),
            preserve_default=False,
        ),
    ]
