# Generated by Django 5.2.4 on 2026-03-03 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talleres", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taller",
            name="cuit",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El CUIT debe contener exactamente 11 dígitos numéricos.",
                        regex="^\\d{11}$",
                    )
                ],
            ),
        ),
    ]
