# Generated by Django 5.2.4 on 2025-11-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talleres", "0002_taller_cuit_taller_horarioatencion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taller",
            name="horarioAtencion",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
