# Generated by Django 5.2.4 on 2026-03-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agendas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenDeTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fecha_turno", models.DateTimeField()),
                ("fecha_entrega", models.DateField(blank=True, null=True)),
                ("kilometraje", models.PositiveIntegerField(blank=True, default=0)),
                ("observaciones_tecnicas", models.TextField(blank=True, null=True)),
                ("fecha_siguiente_servicio", models.DateField(blank=True, null=True)),
                (
                    "kilometraje_siguiente_servicio",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "mantenimiento",
                    models.CharField(
                        choices=[("preventivo", "Preventivo"), ("correctivo", "Correctivo")],
                        default="preventivo",
                        max_length=15,
                    ),
                ),
                ("responsable_tecnico", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "agenda",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes",
                        to="agendas.agenda",
                    ),
                ),
            ],
        ),
    ]
