# Generated by Django 6.0.2 on 2026-02-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='tecnico',
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='responsable_tecnico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
