# Generated by Django 5.2.4 on 2026-02-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordenes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordendetrabajo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("en_proceso", "En proceso"),
                    ("finalizada", "Finalizada"),
                    ("anulada", "Anulada"),
                ],
                db_index=True,
                default="pendiente",
                max_length=15,
            ),
        ),
    ]
