# Generated by Django 5.2.4 on 2026-03-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="sabado",
            field=models.BooleanField(default=True),
        ),
    ]
