# Generated by Django 5.2.4 on 2026-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='turnos_maximos_por_hora',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
