# Generated by Django 5.2.4 on 2026-02-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_alter_agenda_turnos_maximos_por_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='horario_desde',
            field=models.TimeField(default='07:00'),
        ),
    ]
