# Generated by Django 5.2.4 on 2026-02-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendas", "0003_alter_agenda_horario_desde"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="sabado",
            field=models.BooleanField(default=True),
        ),
    ]
