# Generated by Django 5.2.4 on 2026-03-03 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notificaciones", "0001_initial"),
        ("usuarios", "0001_initial"),
        ("vehiculos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationjob",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.cliente"
            ),
        ),
        migrations.AddField(
            model_name="notificationjob",
            name="vehiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vehiculos.vehiculo"
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="notificaciones.notificationjob",
            ),
        ),
    ]
