# Generated by Django 5.2.4 on 2026-03-02 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
        ("vehiculos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="permisodeacceso",
            name="vehiculo_autorizado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="vehiculos.vehiculo",
            ),
        ),
    ]
