# Generated by Django 5.2.4 on 2025-12-01 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
