# Generated by Django 5.2.4 on 2026-03-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="whatsapp_opt_in",
            field=models.BooleanField(default=True),
        ),
    ]
