# Generated by Django 5.2.4 on 2026-03-03 18:14

import usuarios.models.usuario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="dni",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[usuarios.models.usuario.Usuario.validate_dni_numeric],
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
