# Generated by Django 5.2.4 on 2026-03-03 19:09

import usuarios.models.usuario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_usuario_dni_alter_usuario_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="dni",
            field=models.CharField(
                unique=True, validators=[usuarios.models.usuario.Usuario.validate_dni_numeric]
            ),
        ),
    ]
