# Generated by Django 5.2.4 on 2025-12-02 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_cliente_usuario'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisodeacceso',
            name='vehiculo_autorizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehiculos.vehiculo'),
        ),
    ]
