# Generated by Django 5.2.4 on 2026-02-26 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_initial"),
        ("vehiculos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="propietario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehiculos",
                to="usuarios.cliente",
            ),
        ),
    ]
